AI_TERMS = [
    # General terms
    r"\bAI\b",
    r"artificial intelligence",
    r"machine learning",
    r"deep learning",
    r"\bML\b",
    r"\bDL\b",
    r"computer vision",
    r"\bCV\b",
    r"\bNLP\b",
    r"natural language processing",
    # r"predictive analytics",
    # r"expert system",
    # r"knowledge representation",
    # r"symbolic AI",
    # r"semantic web",
    # r"ontolog(y|ies)",
    #
    # # Learning paradigms
    # r"supervised learning",
    # r"unsupervised learning",
    # r"semi[- ]supervised learning",
    # r"self[- ]supervised learning",
    # r"reinforcement learning",
    # r"\bRL\b",
    # r"transfer learning",
    # r"meta[- ]learning",
    # r"federated learning",
    # r"online learning",
    # r"active learning",
    # r"few[- ]shot learning",
    # r"zero[- ]shot learning",
    # r"multi[- ]task learning",
    # r"ensemble learning",
    #
    # # Neural architectures
    # r"\bCNN\b",
    # r"convolutional neural network",
    # r"\bRNN\b",
    # r"recurrent neural network",
    # r"\bLSTM\b",
    # r"\bGRU\b",
    # r"transformer",
    # r"self[- ]attention",
    # r"attention mechanism",
    # r"autoencoder",
    # r"variational autoencoder",
    # r"\bVAE\b",
    # r"\bGAN\b",
    # r"generative adversarial network",
    # r"capsule network",
    # r"graph neural network",
    # r"\bGNN\b",
    # r"neural architecture search",
    #
    # # Probabilistic & statistical models
    # r"Bayesian network",
    # r"Markov (decision process|chain)",
    # r"hidden Markov model",
    # r"\bHMM\b",
    # r"Gaussian mixture model",
    # r"\bGMM\b",
    # r"support vector machine",
    # r"\bSVM\b",
    # r"decision tree",
    # r"random forest",
    # r"gradient boosting",
    # r"XGBoost",
    # r"LightGBM",
    # r"CatBoost",
    # r"k[- ]means clustering",
    # r"hierarchical clustering",
    # r"PCA",
    # r"principal component analysis",
    # r"t[- ]SNE",
    # r"UMAP",
    #
    # # Language & text
    # r"language model",
    # r"\bLLM\b",
    # r"large language model",
    # r"\bBERT\b",
    # r"\bGPT\b",
    # r"ChatGPT",
    # r"text[- ]to[- ]speech",
    # r"speech[- ]to[- ]text",
    # r"speech recognition",
    # r"text summarization",
    # r"sentiment analysis",
    # r"question answering",
    # r"topic modeling",
    # r"\bLDA\b",
    # r"word2vec",
    # r"glove",
    # r"embedding",
    # r"tokenization",
    # r"natural language generation",
    # r"\bNLG\b",
    #
    # # Vision & perception
    # r"object detection",
    # r"semantic segmentation",
    # r"instance segmentation",
    # r"optical character recognition",
    # r"\bOCR\b",
    # r"image classification",
    # r"face recognition",
    #
    # # Robotics & control
    # r"autonomous vehicle",
    # r"robotics",
    # r"robot motion planning",
    # r"motion planning",
    # r"computer graphics",
    #
    # # Applications & others
    # r"recommendation system",
    # r"collaborative filtering",
    # r"content[- ]based filtering",
    # r"anomaly detection",
    # r"time series forecasting",
    # r"financial modeling",
    # r"algorithmic trading",
    # r"autoML",
    # r"hyperparameter tuning",
    # r"explainable AI",
    # r"\bXAI\b",
    # r"interpretable machine learning",
    # r"fuzzy logic",
    # r"swarm intelligence",
    # r"genetic algorithm",
    # r"evolutionary algorithm",
    # r"Monte Carlo tree search",
    # r"knowledge graph",
    # r"edge (AI|computing)",
    # r"Internet of Things",
]

SKIP_REPORTS = ['annual_txts_fitz/Germany/11.BMW_$55.03 B_Industrials/2023/results.txt', 'annual_txts_fitz/China/12.CATL_$115.41 B_Industrials/2021/results.txt', 'annual_txts_fitz/China/12.CATL_$115.41 B_Industrials/2020/results.txt', 'annual_txts_fitz/China/12.CATL_$115.41 B_Industrials/2018/results.txt', 'annual_txts_fitz/China/19.BYD_$98.15 B_Industrials/2022/results.txt', 'annual_txts_fitz/China/19.BYD_$98.15 B_Industrials/2023/results.txt', 'annual_txts_fitz/China/19.BYD_$98.15 B_Industrials/2021/results.txt', 'annual_txts_fitz/China/19.BYD_$98.15 B_Industrials/2020/results.txt', 'annual_txts_fitz/India/2.Tata Consultancy Services_$189.90 B_Information Tech/2016/results.txt', 'annual_txts_fitz/India/6.State Bank of India_$91.89 B_Financials/2014/results.txt', 'annual_txts_fitz/India/6.State Bank of India_$91.89 B_Financials/2015/results.txt', 'annual_txts_fitz/India/6.State Bank of India_$91.89 B_Financials/2017/results.txt', 'annual_txts_fitz/India/6.State Bank of India_$91.89 B_Financials/2016/results.txt', 'annual_txts_fitz/India/19.Axis Bank_$42.72 B_Financial Service/2019/results.txt', 'annual_txts_fitz/India/8.Life Insurance Corporation of India_$89.05 B_Financials/2023/results.txt']
